#local

#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}

#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#spring.mail.host=${MAIL_HOST}
#spring.mail.port=${MAIL_PORT}
#spring.mail.username=${MAIL_USERNAME}
#spring.mail.password=${MAIL_PASSWORD}

#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

#logging.level.root=INFO


#production

# ========================
# DATABASE (RAILWAY)
# ========================
spring.datasource.url=jdbc:postgresql://postgres.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=anYNAUVgmgVZMpIeAfkpajxHPcOayAMa
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ========================
# LOGGING
# ========================
logging.level.root=INFO

# ========================
# RESEND EMAIL (NEW SYSTEM)
# ========================
resend.api.key=re_aN1yj9vx_euSqo92U32neFWnCwU4rocNc
resend.from=Malkris <connect@malkris.com>